---
- hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Install Apache 
      apt: pkg=apache2 state=latest update_cache=yes
      become: true

    - name: Install nginx 
      apt: pkg=nginx state=latest update_cache=yes
      become: true

    - name: Install Java
      apt: pkg=openjdk-17-jre-headless state=latest update_cache=yes
      become: true

    - name: Install MySQL-server
      apt: pkg=mysql-server state=latest update_cache=yes
      become: true

    - name: Install MySQL-client
      apt: pkg=mysql-client state=latest update_cache=yes
      become: true

    - name: Init MySQL
      command: /etc/init.d/mysql start
      become: true

    - name: download tomcat server package
      get_url:
        url: http://dlcdn.apache.org/tomcat/tomcat-10/v10.0.16/bin/apache-tomcat-10.0.16.tar.gz
        dest: /usr/local

    - name: Extract tomcat package
      unarchive:
        src: /usr/local/apache-tomcat-10.0.16.tar.gz
        dest: /usr/local
        remote_src: yes
...
